name: limesdr-grc
version: 3.7.11.1.0
summary: LimeSuite + GRC
description: LimeSuite driver, SoapySDR, GRC, DTV demo, RDS, DRM
confinement: strict
grade: stable

environment:
    LIME_SUITE_ROOT: $SNAP
    SOAPY_SDR_ROOT: $SNAP
    APPDATA: $SNAP_USER_COMMON
    GRC_BLOCKS_PATH: $SNAP/share/gnuradio/grc/blocks
    VOLK_CONFIGPATH: $SNAP_USER_COMMON
    VOLK_PREFIX: $SNAP
    GR_PREFIX: $SNAP
    PYTHONPATH: $SNAP/lib/python2.7/dist-packages/

apps:

    SoapySDRUtil:
        command: SoapySDRUtil
        plugs: [network]

    gnuradio-companion:
        command: desktop-launch gnuradio-companion
        plugs: [network, network-bind, x11, opengl, home]

    gnuradio-config-info:
        command: gnuradio-config-info

    volk-config-info:
        command: volk-config-info

    volk-profile:
        command: volk_profile

    osmocom-fft:
        command: desktop-launch osmocom_fft
        plugs: [network, network-bind, x11, opengl, home]

    osmocom-siggen:
        command: desktop-launch osmocom_siggen
        plugs: [network, network-bind, x11, opengl, home]

parts:
    soapysdr:
        plugin: cmake
        source: https://github.com/pothosware/SoapySDR.git
        source-branch: maint
        configflags:
            - -DENABLE_PYTHON3=OFF
            - -DENABLE_PYTHON=OFF

    soapyremote:
        plugin: cmake
        source: https://github.com/pothosware/SoapyRemote.git
        source-branch: maint
        after: [soapysdr]

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        source-branch: stable
        configflags:
            - -DENABLE_GUI=OFF
            - -DDOWNLOAD_IMAGES=TRUE
        after: [soapysdr]
        build-packages:
            - libsqlite3-dev
            - libi2c-dev
            - libusb-1.0-0-dev

    volk:
        plugin: cmake
        source: https://github.com/gnuradio/volk.git
        source-branch: master #must be master for now for VOLK_PREFIX
        build-packages: [libboost-all-dev, liborc-0.4-dev]
        after: [pythonmodules]

    gnuradio:
        plugin: cmake
        source: https://github.com/gnuradio/gnuradio.git
        source-branch: maint
        build-packages:
            - python-dev
            - libasound2-dev
            - libboost-all-dev
            - libcodec2-dev
            - libcomedi-dev
            - libfftw3-dev
            - libfontconfig1-dev
            - libgsl-dev
            - libgsm1-dev
            - libjack-jackd2-dev
            - liblog4cpp5-dev
            - libpulse-dev
            - libqt4-dev
            - libqwt5-qt4-dev
            - libsdl1.2-dev
            - libsndfile1-dev
            - libxi-dev
            - libxrender-dev
            - libzmq3-dev
            - portaudio19-dev
        configflags:
            - -DENABLE_TESTING=OFF
            - -DENABLE_INTERNAL_VOLK=OFF
            - -DENABLE_DOXYGEN=OFF
            - -DENABLE_SPHINX=OFF
            - -DENABLE_GR_UHD=OFF
            - -DENABLE_GR_QTGUI=OFF
            - -DPYTHON_EXECUTABLE=/usr/bin/python

        after: [desktop-gtk3, volk]

        install: |
            sed -i 's|/usr/bin/|/usr/bin/env |g' $SNAPCRAFT_PART_INSTALL/bin/*

    grosmosdr:
        plugin: cmake
        source: git://git.osmocom.org/gr-osmosdr
        after: [soapysdr, gnuradio]

    grrds:
        plugin: cmake
        source: https://github.com/bastibl/gr-rds.git
        after: [gnuradio]

    grdrm:
        plugin: cmake
        source: https://github.com/kit-cel/gr-drm.git
        after: [gnuradio]

    pythonmodules:
        plugin: dump
        source: .
        organize:
            wx.pth: usr/lib/wx/python/wx.pth
        stage-packages:
            - python
            - python-six
            - python-opengl
            - python-cheetah
            - python-mako
            - python-numpy
            - python-scipy
            - python-gtk2
            - python-lxml
            - python-wxgtk3.0
            - python-wxversion
            - python-zmq
            - python-qwt5-qt4
            - swig
