name: limesuite
version: 19.01.0.0
summary: LimeSuite apps
description: LimeSuite command line utility and Graphical eval app.
confinement: strict
grade: stable

environment:
    LIME_SUITE_ROOT: $SNAP

apps:
    LimeUtil:
        command: LimeUtil
        plugs: [network, home, raw-usb]

    LimeQuickTest:
        command: desktop-launch LimeQuickTest
        plugs: [unity7, opengl, raw-usb]

    LimeSuiteGUI:
        command: desktop-launch LimeSuiteGUI
        plugs: [network, home, unity7, opengl, raw-usb]
parts:

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        source-branch: stable
        after: [desktop-gtk2]
        configflags:
            - -DENABLE_SOAPY_LMS7=OFF
            - -DDOWNLOAD_IMAGES=TRUE
            - -DENABLE_EXAMPLES=OFF
            - -DENABLE_UTILITIES=OFF
            - -DENABLE_HEADERS=OFF
            - -DENABLE_SIMD_FLAGS=SSE3
        build-packages:
            - libwxgtk3.0-dev
            - libfltk1.3-dev
            - libusb-1.0-0-dev
