name: limesdr-pothos 
version: 0.6.1.1
summary: LimeSuite + Pothos apps
description: LimeSuite driver, SoapySDR, Pothos GUI, BTLE Demo
confinement: strict
grade: stable

environment:
    LIME_SUITE_ROOT: $SNAP
    SOAPY_SDR_ROOT: $SNAP
    POTHOS_ROOT: $SNAP
    APPDATA: $SNAP_USER_COMMON

apps:

    SoapySDRUtil:
        command: SoapySDRUtil
        plugs: [network, network-bind, home, raw-usb]

    PothosUtil:
        command: PothosUtil
        plugs: [network, network-bind, home, raw-usb]

    PothosGui:
        command: desktop-launch PothosFlow
        plugs: [network, network-bind, x11, opengl, home, raw-usb]

parts:
    soapysdr:
        plugin: cmake
        source: https://github.com/pothosware/SoapySDR.git
        source-branch: maint
        configflags:
            - -DENABLE_PYTHON3=OFF
            - -DENABLE_PYTHON=OFF

    soapyremote:
        plugin: cmake
        source: https://github.com/pothosware/SoapyRemote.git
        source-branch: maint
        after: [soapysdr]

    limesuite:
        plugin: cmake
        source: https://github.com/myriadrf/LimeSuite.git
        source-branch: stable
        configflags:
            - -DENABLE_GUI=OFF
            - -DDOWNLOAD_IMAGES=TRUE
            - -DENABLE_EXAMPLES=OFF
            - -DENABLE_UTILITIES=OFF
            - -DENABLE_SIMD_FLAGS=SSE3
        after: [soapysdr]
        build-packages:
            - libusb-1.0-0-dev

    poco:
        plugin: cmake
        source: https://github.com/pocoproject/poco.git
        source-tag: poco-1.7.5-release

    muparserx:
        plugin: cmake
        source: https://github.com/beltoforion/muparserx.git
        source-tag: v4.0.7
        configflags: ["-DBUILD_SHARED_LIBS=ON"]

    spuce:
        plugin: cmake
        source: https://github.com/audiofilter/spuce.git
        source-tag: "0.4.3"
        configflags:
            - -DBUILD_SHARED_LIBS=ON
            - -DBUILD_TESTING=OFF
            - -DENABLE_PYTHON=OFF

    pothosserialization:
        plugin: cmake
        source: https://github.com/pothosware/pothos-serialization.git
        source-branch: maint

    pothosframework:
        plugin: cmake
        source: https://github.com/pothosware/pothos.git
        source-branch: maint
        configflags:
            - -DENABLE_TOOLKITS=OFF
            - -DENABLE_INTERNAL_POCO=OFF
            - -DENABLE_INTERNAL_SPUCE=OFF
            - -DENABLE_INTERNAL_MUPARSERX=OFF
            - -DENABLE_INTERNAL_SERIALIZATION=OFF
        after: [poco, pothosserialization, muparserx]
        build-packages: [libnuma-dev]

    pothossdr:
        plugin: cmake
        source: https://github.com/pothosware/pothos-sdr.git
        source-branch: maint
        after: [pothosframework, soapysdr]

    pothosaudio:
        plugin: cmake
        source: https://github.com/pothosware/pothos-audio.git
        source-branch: master
        after: [pothosframework]
        build-packages: [portaudio19-dev, libjack-jackd2-dev]

    pothosblocks:
        plugin: cmake
        source: https://github.com/pothosware/pothos-blocks.git
        source-branch: maint
        after: [pothosframework]

    pothoscomms:
        plugin: cmake
        source: https://github.com/pothosware/pothos-comms.git
        source-branch: maint
        after: [pothosframework, spuce]

    pothosgui:
        plugin: cmake
        source: https://github.com/pothosware/pothos-gui.git
        source-branch: maint
        after: [pothosframework, desktop-qt5]
        build-packages: [qtbase5-dev]

    pothosplotters:
        plugin: cmake
        source: https://github.com/pothosware/pothos-plotters.git
        source-branch: maint
        after: [pothosframework, spuce]
        build-packages: [qtbase5-dev, libqt5svg5-dev, libqt5opengl5-dev, libqwt-qt5-dev]

    pothoswidgets:
        plugin: cmake
        source: https://github.com/pothosware/pothos-widgets.git
        source-branch: master
        after: [pothosframework]
        build-packages: [qtbase5-dev, libqt5svg5-dev, libqt5opengl5-dev]

    btledemo:
        plugin: cmake
        source: https://github.com/DesignSparkrs/sdr-ble-demo.git
        after: [pothosframework]
