name: gpredict
version: 2.2.1
summary: Gpredict - satellite tracking
description: Gpredict is a real time satellite tracking and orbit prediction program for the Linux desktop. It uses the SGP4/SDP4 propagation algorithms together with NORAD two-line element sets (TLE).
confinement: devmode
grade: stable

apps:
    gpredict:
        command: desktop-launch gpredict
        plugs: [network, network-bind, opengl, home, desktop, gsettings, unity7]

parts:

    gpredict:
        plugin: autotools
        source: https://github.com/csete/gpredict/releases/download/v2.2.1/gpredict-2.2.1.tar.bz2
        after: [desktop-gtk3]
        build-packages:
            - libgtk-3-dev
            - libcurl4-openssl-dev
            - libglib2.0-dev
            - libgoocanvas-2.0-dev
        stage-packages:
            - libgdk-pixbuf2.0-common 
            - libgdk3.0-cil
            - libgtk-3-0
            - libcurl3
            - libglib2.0-dev
            - libgoocanvas-2.0-9
            - libpango-1.0-0
            - libpangocairo-1.0-0
            - libcanberra-gtk-module
            - libcanberra-gtk3-module
            - unity-gtk-module-common
            - libgl1-mesa-glx
